###
POST http://localhost:8081/api/user/login HTTP/1.1
Content-Type: application/json

{
  "email":""
}

###
POST http://localhost:8081/api/todos/5fb4445e19be8d00042e6da0/update_step HTTP/1.1
Content-Type: application/json

{
  "step": {
    "_id": "5fb4445e19be8d00042e6da3",
    "status": "working",
    "name": "工作",
    "idx": 0
  },
  "mode": "update"
}

###
POST http://localhost:8081/api/visuals/imdb_boxoffice HTTP/1.1
Content-Type: application/json

{
  
}

###
POST http://localhost:8081/api/visuals/douban HTTP/1.1
Content-Type: application/json

{
  "limit": 30,
  "page": 1
}

###
POST http://localhost:8081/api/visuals/douban/tags HTTP/1.1
Content-Type: application/json

{
  "type": "movie"
}

###
POST http://localhost:8081/api/visuals/in_theatre HTTP/1.1
Content-Type: application/json

{
  "city": "beijing"
}

###
POST http://localhost:8081/api/visuals/search HTTP/1.1
Content-Type: application/json

{
  "keyword": "美国队长"
}

###
POST http://localhost:8081/api/visuals/summary HTTP/1.1
content-type: application/json

{
  "douban_id": "25907124"
}
//25907124

###
POST http://localhost:8081/api/visuals/photos HTTP/1.1
content-type: application/json

{
  "douban_id": 30467486,
  "page": 1,
  "type": "S"
}

###
POST http://localhost:8081/api/visuals/photo HTTP/1.1
content-type: application/json

{
  "photo_id": 2619516174
}

###
POST http://localhost:8081/api/visuals/celebrities HTTP/1.1
content-type: application/json

{
  "douban_id":26100958
}

###
POST http://localhost:8081/api/visuals/cast HTTP/1.1
content-type: application/json

{
  "cast_id":1016681
}

###
POST http://localhost:8081/api/visuals/comments HTTP/1.1
content-type: application/json

{
  "douban_id":26100958
}

###
POST http://localhost:8081/api/visuals/reviews HTTP/1.1
content-type: application/json

{
  "douban_id":25907124
}

###
POST http://localhost:8081/api/transactions HTTP/1.1
content-type: application/json

{
  "date":"2020",
  "category":{
    "$in":["internet"]
  }
}

###
GET http://localhost:8081/api/places/update_random HTTP/1.1
